### ISSUE TITLE
Issue about Data Generation

### ISSUE THREAD

**Issue by 55Dupup** [zhouxian/act3d-chained-diffuser#23]
Thank you for your excellent work. When generating data, I encountered the following error. How should I solve it?

> Traceback (most recent call last):
  File "/data/55d_1/act3d-chained-diffuser/data_preprocessing/dataset_generator.py", line 511, in <module>
    app.run(main)
  File "/home/dell/anaconda3/envs/chained_diffuser/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/dell/anaconda3/envs/chained_diffuser/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/data/55d_1/act3d-chained-diffuser/data_preprocessing/dataset_generator.py", line 500, in main
    run_all_variations(
  File "/data/55d_1/act3d-chained-diffuser/data_preprocessing/dataset_generator.py", line 374, in run_all_variations
    rlbench_env.launch()
  File "/data/55d_1/act3d-chained-diffuser/RLBench/rlbench/environment.py", line 110, in launch
    arm, gripper = arm_class(), gripper_class()
  File "/data/55d_1/act3d-chained-diffuser/PyRep/pyrep/robots/arms/panda.py", line 7, in __init__
    super().__init__(count, 'Panda', 7)
  File "/data/55d_1/act3d-chained-diffuser/PyRep/pyrep/robots/arms/arm.py", line 25, in __init__
    super().__init__(count, name, joint_names, base_name)
  File "/data/55d_1/act3d-chained-diffuser/PyRep/pyrep/robots/robot_component.py", line 19, in __init__
    super().__init__(
  File "/data/55d_1/act3d-chained-diffuser/PyRep/pyrep/objects/object.py", line 24, in __init__
    self._handle = sim.simGetObjectHandle(name_or_handle)
  File "/data/55d_1/act3d-chained-diffuser/PyRep/pyrep/backend/sim.py", line 94, in simGetObjectHandle
    raise RuntimeError('Handle %s does not exist.' % objectName)
RuntimeError: Handle Panda does not exist.

**Comment by Viswesh-N** [comment]
Hey,
Did this issue get resolved?

**Comment by yuanzhi1209** [comment]
install the correct CoppeliaSim version
