### ISSUE TITLE
Missing trajectory generation in data_preprocessing

### ISSUE THREAD

**Issue by rakhimovv** [zhouxian/act3d-chained-diffuser#7]
Hi, thanks for your work and the published code.

When running `data_preprocessing/compute_workspace_bounds.py`, the following error occurs:

```
Exception has occurred: IndexError

index 5 is out of bounds for axis 0 with size 5
  File "/projects/act3d-chained-diffuser/datasets/dataset_engine.py", line 240, in <listcomp>
    self._interpolate_traj(episode[5][i]) for i in frame_ids
  File "/projects/act3d-chained-diffuser/datasets/dataset_engine.py", line 239, in __getitem__
    traj_items = [
  File "/projects/act3d-chained-diffuser/data_preprocessing/compute_workspace_bounds.py", line 85, in <module>
    ep = dataset[i]
IndexError: index 5 is out of bounds for axis 0 with size 5
```
This error is due to missing trajectory generation in [data_preprocessing/data_gen.py](https://github.com/zhouxian/act3d-chained-diffuser/blob/main/data_preprocessing/data_gen.py#L157)

**Comment by rakhimovv** [comment]
`main_trajectory.py` also fails due to this error

![image](https://github.com/zhouxian/act3d-chained-diffuser/assets/14886513/db20d81a-5200-40b6-890d-f282e0fa6655)

**Comment by LemonWade** [comment]
I also encountered the same problem

**Comment by ZXP-S-works** [comment]
I also encountered similar problem in 
```
Created dataset from ***/act3d-chained-diffuser/data/packaged/18_peract_tasks_train with 3
Computing gripper location bounds for task place_wine_at_rack_location from dataset of length 3
Traceback (most recent call last):
  File "***/envs/chained_diffuser/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "***/envs/chained_diffuser/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "***/act3d-chained-diffuser/data_preprocessing/compute_workspace_bounds.py", line 81, in <module>
    ep = dataset[i]
  File "***/act3d-chained-diffuser/datasets/dataset_engine.py", line 213, in __getitem__
    traj_items = [
  File "***/act3d-chained-diffuser/datasets/dataset_engine.py", line 214, in <listcomp>
    self._interpolate_traj(episode[5][i]) for i in frame_ids
IndexError: index 5 is out of bounds for axis 0 with size 5

```

Does anyone know how to solve it?

Thanks,
XP

**Comment by ZXP-S-works** [comment]
Is there any updates?

**Comment by nickgkan** [comment]
A fix will be pushed tomorrow (Jan 6th).

**Comment by yuelei0428** [comment]
Hi has this been fixed now? I encountered the same error.

**Comment by nickgkan** [comment]
Hi everyone, we updated the data generation/preprocessing scripts. Please refer to the corresponding README. We fixed:

1. including the trajectory data to the packaged annotations
2. rejecting demos with failures or inconsistencies.

I hope this solves everyone's issues, please re-open if you encounter another error.
Thanks everyone for your interest in this project!
